name: DEPLOYMENT
on: deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy"
      - name: Update deployment status
        if: success()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.BOT_GITHUB_TOKEN}}
          script: |
            github.repos.createDeploymentStatus({
              deployment_id: context.payload.deployment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "success"
            })
