name: DEPLOYMENT
on: deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy"
      - name: Update deployment status
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const jobStatus = '${{ job.status }}'
            const deployStateSuccess = 'success'
            const deployStateFailure = 'failure'
            const deployStatePending = 'pending'

            let deployState = deployStatePending 
            if (jobStatus == 'Success') {
              deployState = deployStateSuccess
            } else if  (jobStatus == 'Failure') {
              deployState = deployStateFailure
            }

            github.repos.createDeploymentStatus({
              deployment_id: context.payload.deployment.id,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: deployState
            })
