name: TAG
on:
  push:
    branches:
      - develop
      - master
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
      # 不要と判断
      # - '!*-sdk-*'
    # tags と tags-ignore は同時には使えない
    # tags-ignore:
    #   - '*-sdk-*'
  # Github の Releases から作成した際も push イベント(tag)が実行される
  # release:
  #   types:
  #     - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: develop
        if: github.ref == 'refs/heads/develop'
        run: echo "develop"
      - name: master
        if: github.ref == 'refs/heads/master'
        run: echo "master"
      - name: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "tag"
